[2024-04-05T16:07:36.473+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-05T16:07:36.887+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-05T16:07:36.902+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-05T16:07:36.905+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-05T16:07:36.923+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-05T16:07:37.936+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): runme_2> on 2024-04-03 00:00:00+00:00
[2024-04-05T16:07:38.386+0000] {standard_task_runner.py:55} INFO - Started process 3181 to run task
[2024-04-05T16:07:38.674+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'runme_2', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpnh63s1yb']
[2024-04-05T16:07:38.696+0000] {standard_task_runner.py:83} INFO - Job 96: Subtask runme_2
[2024-04-05T16:07:42.931+0000] {task_command.py:376} INFO - Running <TaskInstance: example_bash_operator.runme_2 scheduled__2024-04-03T00:00:00+00:00 [running]> on host a868c0c748e3
[2024-04-05T16:08:05.446+0000] {local_task_job.py:221} WARNING - DagRun timed out after 1 day, 12:16:00.561805.
[2024-04-05T16:08:16.098+0000] {local_task_job.py:221} WARNING - DagRun timed out after 1 day, 12:16:11.087424.
[2024-04-05T16:08:16.349+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2024-04-05T16:08:15.848+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_2
AIRFLOW_CTX_EXECUTION_DATE=2024-04-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-03T00:00:00+00:00
[2024-04-05T16:08:17.468+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-04-05T16:08:17.486+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "example_bash_operator__runme_2__20240403" && sleep 1']
[2024-04-05T16:08:17.438+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 3181. PIDs of all processes in the group: [3181]
[2024-04-05T16:08:17.606+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 3181
[2024-04-05T16:08:17.899+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-05T16:08:17.970+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-04-05T16:08:18.073+0000] {logging_mixin.py:120} WARNING - Exception ignored in: <function _releaseLock at 0x7f32288dd170>
[2024-04-05T16:08:18.086+0000] {logging_mixin.py:120} WARNING - Traceback (most recent call last):
[2024-04-05T16:08:18.105+0000] {logging_mixin.py:120} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 221, in _releaseLock
[2024-04-05T16:08:18.305+0000] {logging_mixin.py:120} WARNING -     def _releaseLock():
[2024-04-05T16:08:18.452+0000] {logging_mixin.py:120} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1564, in signal_handler
[2024-04-05T16:08:18.505+0000] {logging_mixin.py:120} WARNING -     raise AirflowException("Task received SIGTERM signal")
[2024-04-05T16:08:18.541+0000] {logging_mixin.py:120} WARNING - ***.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-05T16:08:18.718+0000] {subprocess.py:86} INFO - Output:
[2024-04-05T16:08:18.832+0000] {subprocess.py:93} INFO - example_bash_operator__runme_2__20240403
[2024-04-05T16:08:20.625+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-05T16:08:25.694+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20240403T000000, start_date=20240405T160736, end_date=20240405T160825
[2024-04-05T16:08:29.867+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3181, status='terminated', exitcode=0, started='16:07:37') (3181) terminated with exit code 0
