[2024-04-09T15:02:13.401+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-09T15:02:13.515+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-09T15:02:13.520+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-09T15:02:13.527+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-09T15:02:13.529+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-09T15:02:13.689+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-04-08 00:00:00+00:00
[2024-04-09T15:02:13.756+0000] {standard_task_runner.py:55} INFO - Started process 10247 to run task
[2024-04-09T15:02:13.829+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2024-04-08T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp42a09v5x']
[2024-04-09T15:02:13.846+0000] {standard_task_runner.py:83} INFO - Job 165: Subtask create_table
[2024-04-09T15:02:15.299+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2024-04-08T00:00:00+00:00 [running]> on host a868c0c748e3
[2024-04-09T15:02:16.475+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-04-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-08T00:00:00+00:00
[2024-04-09T15:02:16.636+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-04-09T15:02:16.703+0000] {sql.py:315} INFO - Running statement: 
			CREATE TABLE IF NOT EXISTS users (
				firstname TEXT NOT NULL,
				lastname TEXT NOT NULL,
				country TEXT NOT NULL,
				username TEXT NOT NULL,
				password TEXT NOT NULL,
				email TEXT NOT NULL
			);
		, parameters: None
[2024-04-09T15:02:16.726+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-04-09T15:02:16.820+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240408T000000, start_date=20240409T150213, end_date=20240409T150216
[2024-04-09T15:02:17.211+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-04-09T15:02:17.806+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-09T15:02:18.492+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: user_processing.create_table scheduled__2024-04-08T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-04-09T15:02:18.580+0000] {local_task_job.py:103} INFO - Task is not able to be run
