[2024-04-11T15:17:12.245+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-10T00:00:00+00:00 [queued]>
[2024-04-11T15:17:12.819+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-10T00:00:00+00:00 [queued]>
[2024-04-11T15:17:12.876+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-11T15:17:12.879+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-11T15:17:12.887+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-11T15:17:13.940+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-04-10 00:00:00+00:00
[2024-04-11T15:17:14.482+0000] {standard_task_runner.py:55} INFO - Started process 16266 to run task
[2024-04-11T15:17:15.043+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2024-04-10T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpo21z5l4c']
[2024-04-11T15:17:15.115+0000] {standard_task_runner.py:83} INFO - Job 193: Subtask create_table
[2024-04-11T15:17:18.693+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2024-04-10T00:00:00+00:00 [running]> on host a868c0c748e3
[2024-04-11T15:17:21.197+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-04-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-10T00:00:00+00:00
[2024-04-11T15:17:21.751+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-04-11T15:17:21.830+0000] {sql.py:315} INFO - Running statement: 
			CREATE TABLE IF NOT EXISTS users (
				firstname TEXT NOT NULL,
				lastname TEXT NOT NULL,
				country TEXT NOT NULL,
				username TEXT NOT NULL,
				password TEXT NOT NULL,
				email TEXT NOT NULL
			);
		, parameters: None
[2024-04-11T15:17:21.856+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-04-11T15:17:22.196+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240410T000000, start_date=20240411T151712, end_date=20240411T151722
[2024-04-11T15:17:25.237+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-04-11T15:17:26.499+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-11T15:17:26.460+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: user_processing.create_table scheduled__2024-04-10T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-04-11T15:17:27.091+0000] {local_task_job.py:103} INFO - Task is not able to be run
