[2024-04-14T06:40:16.987+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T06:40:17.269+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T06:40:17.273+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-14T06:40:17.276+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-14T06:40:17.278+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-14T06:40:17.430+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-04-13 00:00:00+00:00
[2024-04-14T06:40:17.591+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpsvtx8isk']
[2024-04-14T06:40:17.597+0000] {standard_task_runner.py:83} INFO - Job 253: Subtask create_table
[2024-04-14T06:40:17.601+0000] {standard_task_runner.py:55} INFO - Started process 35412 to run task
[2024-04-14T06:40:17.800+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: user_processing.create_table scheduled__2024-04-13T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-04-14T06:40:17.851+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: user_processing.create_table scheduled__2024-04-13T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-04-14T06:40:17.857+0000] {local_task_job.py:103} INFO - Task is not able to be run
[2024-04-14T06:40:18.110+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2024-04-13T00:00:00+00:00 [running]> on host a868c0c748e3
[2024-04-14T06:40:18.941+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-04-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-13T00:00:00+00:00
[2024-04-14T06:40:19.054+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-04-14T06:40:19.113+0000] {sql.py:315} INFO - Running statement: 
			CREATE TABLE IF NOT EXISTS users (
				firstname TEXT NOT NULL,
				lastname TEXT NOT NULL,
				country TEXT NOT NULL,
				username TEXT NOT NULL,
				password TEXT NOT NULL,
				email TEXT NOT NULL
			);
		, parameters: None
[2024-04-14T06:40:19.127+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-04-14T06:40:19.209+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240413T000000, start_date=20240414T064017, end_date=20240414T064019
[2024-04-14T06:40:19.466+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-04-14T06:40:19.785+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
